### ISSUE TITLE
error when trying to run test.js or index.js

### ISSUE THREAD

**Issue by Throwaway992** [tacyarg/bybit#2]
C:\Users\bob\Desktop\bybit-master>node test.js
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'bybit'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\bob\Desktop\bybit-master\index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by tacyarg** [comment]
Run `npm install`

**Comment by Throwaway992** [comment]
Hi, I ran npm install already.
Still the same error

**Comment by Throwaway992** [comment]
I messed around a little with it and got it to work somehow.. thx!
